//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketAll
    {
        public string NameOfProduct { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<double> Sale { get; set; }
        public string Imagin { get; set; }
        public int IDCheck { get; set; }
        public Nullable<int> IDUser { get; set; }
    }
}
