//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check()
        {
            this.ProductCheck = new HashSet<ProductCheck>();
        }
    
        public int IDCheck { get; set; }
        public Nullable<int> IDCofe { get; set; }
        public Nullable<System.DateTime> IssuingTime { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string ISBuy { get; set; }
    
        public virtual Cofe Cofe { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCheck> ProductCheck { get; set; }
    }
}
