//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCheck
    {
        public Nullable<int> IDProduct { get; set; }
        public int IDCheck { get; set; }
        public int idprodcheck { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Product Product { get; set; }
    }
}
